### ISSUE TITLE
Feature request: Negative prompt

### ISSUE THREAD

**Issue by Explosion-Scratch** [carefree0910/carefree-creator#3]
^

Love this project btw

**Comment by carefree0910** [comment]
Very nice advice! I will work on it tomorrow and will notify you once it's published online! 😆

**Comment by carefree0910** [comment]
The `Negative Prompt` is online now! 🥳

> See [this section](https://github.com/carefree0910/carefree-creator#negative-prompt) for more details!

**Comment by Explosion-Scratch** [comment]
Thanks again!
