### ISSUE TITLE
Hey i just want to know what all different models exactly are being used here. Thanks!!

### ISSUE THREAD

**Issue by Ashes47** [carefree0910/carefree-creator#31]
<img width="288" alt="Screenshot 2023-06-11 at 8 31 47 PM" src="https://github.com/carefree0910/carefree-creator/assets/42962743/8c3ca282-7e1a-44a3-9331-c09870897368">

**Comment by Ashes47** [comment]
@carefree0910

**Comment by carefree0910** [comment]
Hi! These models are basically some civiti models, but we did some finetunings on them, so it's hard to say what 'exactly' the models are.

If you are interested in the 'base models':
* General - SD1.5
* Real - Realistic
* Anime - Novel AI
* 3D anime - Anything
* DreamLike Art - Dreamlike

**Comment by Ashes47** [comment]
Thanks a lot!
