### ISSUE TITLE
Using API to generate images

### ISSUE THREAD

**Issue by XplosiON1232** [carefree0910/carefree-creator#37]
Hello! I used to be able to launch it on Colab and then send API requests to the endpoint "/txt2img/sd"

https://example.ngrok.io/txt2img/sd

But now the documentation is gone in "/redoc" and I cant send API requests to the endpoint at all.

I'm sorry if I've missed anything, thank you!

**Comment by carefree0910** [comment]
Hi! Since I've added more and more features to this repo, even the basic `sd` services cannot be launched in a naive Colab due to the memory issue (not GPU RAM, but RAM - there are simply too many models to be loaded 🤣)

So if you scroll down to the bottom of the colab, you'll find that the end of the last LOOOONG command is something like:

```python
os.system('cfcreator serve --limit 1 --focus sync')
```

You can change it to:

```python
os.system('cfcreator serve --limit 1 --focus sd.base')
```

to re-activate the `/txt2img/sd` (and the `/img2img/sd`) endpoint. Beware that this might crush the Colab if the RAM is not enough!

**Comment by XplosiON1232** [comment]
Hey! I tired, and yes, it did indeed hit the RAM limit and crash the Colab 🙃

Is there maybe any way to run an old version of the project on colab? Since I remember it working before.

Thank you.

**Comment by carefree0910** [comment]
Hi! Unfortunately, I'm afraid that 'currently' there isn't a way to do it. 😣 But I'm working on simplifying the start up process under the `sd.base` mode, and once I successfully run it through the Colab, I'll let you know!

**Comment by XplosiON1232** [comment]
Okay, thank you!

**Comment by XplosiON1232** [comment]
Hello! Sorry to disturb you, but there isn't any way to specify an old version of the package when installing in the colab?

For example instead of "pip install carefree-creator" we could do something like "pip install carefree-creator==1.0" or something, to install the old version of the package?

Thank you, and if not, lmk if you manage to fit it in a colab again!

**Comment by carefree0910** [comment]
Oh, never mind! There indeed has a way to specify an old version, and yes, replace `pip install carefree-creator` with `pip install carefree-creator==xxx` can definitely do the job!

Here's the full list of the available versions: https://pypi.org/project/carefree-creator/#history

> The problem is, I'm not sure which version can solve your problem, so I didn't mention it. 🤣

**Comment by carefree0910** [comment]
> Hello! Sorry to disturb you, but there isn't any way to specify an old version of the package when installing in the colab?
> 
> For example instead of "pip install carefree-creator" we could do something like "pip install carefree-creator==1.0" or something, to install the old version of the package?
> 
> Thank you, and if not, lmk if you manage to fit it in a colab again!

Hi! I've just updated the colab, it should be working now. 🥳

Let me know if you face any other issues!

**Comment by XplosiON1232** [comment]
Hey! I tried it and it works great! Thank you very much!
