### ISSUE TITLE
Feature request: Custom domain

### ISSUE THREAD

**Issue by Explosion-Scratch** [carefree0910/carefree-creator#4]
This does allow a custom port, but it'd be nice to have a whole custom endpoint, that way people could host the server on Google Colab then use that as the backend for the webui.

Ideally this would also be used to host images, instead of on your poor server.

Working on a Colab to do just this: https://colab.research.google.com/drive/1JbmQhUloM14aK713ypV2JRdZmV-Fs9le?usp=sharing

(For some reason ngrok doesn't seem to be printing the output URL of the tunnel though)

**Comment by carefree0910** [comment]
Sure! Very nice advice, will add that ASAP 😆

**Comment by carefree0910** [comment]
The feature is online right now! Maybe I'll try to play with Google Colab tomorrow, I'm not familiar with it though...

Once I succeeded (or someone succeeded) in using the Colab as the backend server, it will be super-duper helpful! 😆 I'll definitely treat it as the recommended 'local' deployment method and update the README!

**Comment by carefree0910** [comment]
Ah, silly me, why did I split those stuffs around, maybe I just should not code late in the night 🤣

I've just updated the WebUI, and I've already succeeded in using the Colab as the backend server and have updated the README. Now 'local' deployment should be much easier.

Thanks again for this advice, it is truly helpful! 🥳

**Comment by Explosion-Scratch** [comment]
> Once I succeeded (or someone succeeded) in using the Colab as the backend server, it will be super-duper helpful! 😆 I'll definitely treat it as the recommended 'local' deployment method and update the README!

Wait, you did? I've been trying all morning and it keeps failing

(Updated Python to install numpy, tried to tunnel through ngrok but for some reason it didn't spit out the URL, tried to add parameters to the generate function but kept getting image file errors)

**Comment by Explosion-Scratch** [comment]
lol, looked at your colab notebook and realized I forgot the authtoken for ngrok 🤦🏻
