### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Ashes47** [carefree0910/carefree-creator#6]
Heyy i can help you with your discord community while also tryna help you with the project itself does that sound worth looking into?

**Comment by carefree0910** [comment]
Wow, of course! That's so kind of you 😆

What can I do to help you? Do I need to provide some information?

**Comment by Ashes47** [comment]
Yeah we can connect over discord and take it from there? https://discord.gg/dPnAbT8K @carefree0910

**Comment by carefree0910** [comment]
Sure! 🥳🥳

**Comment by bropines** [comment]
By the way, your discord link is out of date

**Comment by Ashes47** [comment]
Here you go!!! https://discord.gg/pBzCaTWkbK.
