### ISSUE TITLE
POSTing to configured local server fails if URL ends with a trailing slash (`/`)

### ISSUE THREAD

**Issue by anoadragon453** [carefree0910/carefree-creator#7]
Following the instructions of the Google Colab, I generated an ngrok URL that looks like `https://f24d-68-121-167-240.ngrok.io`. Copy-pasting this in Firefox from the Google Colab helpfully formatted it as `https://f24d-68-121-167-240.ngrok.io/` (note the trailing slash).

Putting this into the "Use Local Server" field and clicking "Generate Image" results in a POST request from the browser to `https://f24d-68-121-167-240.ngrok.io//get_prompt` from the browser (note the double forward slashes). The hosted server returns a 404 for this request and the WebUI displays errors:

![image](https://user-images.githubusercontent.com/1342360/198891869-728d4130-bd2a-49d0-9699-3a2b22ceb81e.png)

I suggest that either the WebUI strip trailing slashes from configured Local Server URLs, or the server be able to handle multiple, continuous slashes in a request URL.

**Comment by carefree0910** [comment]
Oops, good catch! I'll definitely strip trailing slashes for you in the WebUI!

I'll notify you once I finished the modification 😉

**Comment by carefree0910** [comment]
@anoadragon453 I think I fixed it; can you refresh the page and try again? 😆

**Comment by anoadragon453** [comment]
I can confirm that it works! Thanks for the swift fix :)
